// Copyright 2025 fsyyft-go
//
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package sms_bridge

import (
	"github.com/fsyyft-go/kit/log"
	"github.com/fsyyft-go/sms-bridge/internal/biz"
	"github.com/fsyyft-go/sms-bridge/internal/config"
	"github.com/fsyyft-go/sms-bridge/internal/server"
	"github.com/fsyyft-go/sms-bridge/internal/service"
)

// Injectors from wire.go:

func wireServer(logger log.Logger, cfg *config.Config) (*server.WebServer, func(), error) {
	smsBiz := biz.NewSmsBiz(logger, cfg)
	smsService := service.NewSmsService(logger, cfg, smsBiz)
	webServer, cleanup, err := server.NewWebServer(logger, cfg, smsService)
	if err != nil {
		return nil, nil, err
	}
	return webServer, func() {
		cleanup()
	}, nil
}
