// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package sms_bridge

import (
	"github.com/fsyyft-go/kit/log"
	"github.com/fsyyft-go/sms-bridge/internal/config"
	"github.com/fsyyft-go/sms-bridge/internal/server"
)

// Injectors from wire.go:

func wireServer(logger log.Logger, cfg *config.Config) (*server.WebServer, func(), error) {
	webServer, cleanup, err := server.NewWebServer(logger, cfg)
	if err != nil {
		return nil, nil, err
	}
	return webServer, func() {
		cleanup()
	}, nil
}
