upstream ssl_message_ppno_net {
    # 应用程序：/data/webservers/tool/message/message
    # 配置文件：/data/webservers/tool/message/message.conf
    server          172.27.70.1:8098;

    # 到后端服务器保持的最大空闲连接数。
    keepalive       128;
}

server {
    listen          80;
    server_name     message.ppno.net message-hz.ppno.net message-inner.ppno.net;
    rewrite         ^(.*)$ https://$host$1 permanent;
    
    access_log      /var/log/nginx/message.ppno.net/-$logdate.log main;
    error_log       /var/log/nginx/message.ppno.net/error.log;
}

server {
    listen          443 ssl http2;
    server_name     message.ppno.net message-hz.ppno.net message-inner.ppno.net;
    
    # 证书相关的通用配置。
    include         /etc/nginx/conf.common/conf.ssl.ppno.net;
    include         /etc/nginx/conf.common/conf.ssl.reinforce;

    # 白名单相关的通用配置。
    include         /etc/nginx/conf.common/conf.ip.fuzhou.allow;
    deny            all;


    access_log      /var/log/nginx/message.ppno.net/ssl_-$logdate.log main;
    error_log       /var/log/nginx/message.ppno.net/ssl_error.log;


    location / {
        proxy_pass  http://ssl_message_ppno_net/;

        # HTTP 和 WebSocket 相关的通用配置。
        include     /etc/nginx/conf.common/conf.proxy.common;
        include     /etc/nginx/conf.common/conf.websocket.common;
    }

    include         /etc/nginx/conf.common/conf.robots.common;
}
