// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.3
// - protoc             v5.29.3
// source: api/sms/sms.proto

package sms

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSmsServiceSendSms = "/api.sms.SmsService/SendSms"

type SmsServiceHTTPServer interface {
	SendSms(context.Context, *SendSmsRequest) (*SendSmsResponse, error)
}

func RegisterSmsServiceHTTPServer(s *http.Server, srv SmsServiceHTTPServer) {
	r := s.Route("/")
	r.GET("sms/bridge/?from={from}&to={to}&message={message}", _SmsService_SendSms0_HTTP_Handler(srv))
	r.GET("sms/bridge", _SmsService_SendSms1_HTTP_Handler(srv))
}

func _SmsService_SendSms0_HTTP_Handler(srv SmsServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendSmsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSmsServiceSendSms)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendSms(ctx, req.(*SendSmsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendSmsResponse)
		return ctx.Result(200, reply)
	}
}

func _SmsService_SendSms1_HTTP_Handler(srv SmsServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendSmsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSmsServiceSendSms)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendSms(ctx, req.(*SendSmsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendSmsResponse)
		return ctx.Result(200, reply)
	}
}

type SmsServiceHTTPClient interface {
	SendSms(ctx context.Context, req *SendSmsRequest, opts ...http.CallOption) (rsp *SendSmsResponse, err error)
}

type SmsServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSmsServiceHTTPClient(client *http.Client) SmsServiceHTTPClient {
	return &SmsServiceHTTPClientImpl{client}
}

func (c *SmsServiceHTTPClientImpl) SendSms(ctx context.Context, in *SendSmsRequest, opts ...http.CallOption) (*SendSmsResponse, error) {
	var out SendSmsResponse
	pattern := "sms/bridge"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSmsServiceSendSms))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
